// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoD93WDmSiNxYXlTvqRMT79DXb1kVWa6g',
    appId: '1:534494408695:web:46d4c9861cd07e89e048f2',
    messagingSenderId: '534494408695',
    projectId: 'ohima-767be',
    authDomain: 'ohima-767be.firebaseapp.com',
    storageBucket: 'ohima-767be.appspot.com',
    measurementId: 'G-1F3Z29GGN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4CbfmUPJa5FmLfr9MzX9xu45Uh8llSc',
    appId: '1:534494408695:android:06787dfa6e111a12e048f2',
    messagingSenderId: '534494408695',
    projectId: 'ohima-767be',
    storageBucket: 'ohima-767be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX0kX1CN81y7wFmOiC2fk6MN9R-hmzY_0',
    appId: '1:534494408695:ios:01017fe7fc6cbaece048f2',
    messagingSenderId: '534494408695',
    projectId: 'ohima-767be',
    storageBucket: 'ohima-767be.appspot.com',
    iosClientId: '534494408695-560ftkqa662o7rl68rqq54neetk1tg3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX0kX1CN81y7wFmOiC2fk6MN9R-hmzY_0',
    appId: '1:534494408695:ios:356fdf597abaf8ebe048f2',
    messagingSenderId: '534494408695',
    projectId: 'ohima-767be',
    storageBucket: 'ohima-767be.appspot.com',
    iosClientId: '534494408695-tba271s5dplrkogck01gnkfqh61dqb9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohima.RunnerTests',
  );
}
